# Generated by Django 3.1.2 on 2020-11-11 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0006_resta_prove'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resta_Prove',
        ),
    ]
