# Generated by Django 3.1.2 on 2020-11-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0007_delete_resta_prove'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Hotel')),
                ('client', models.CharField(max_length=100, verbose_name='Nombre Cliente')),
                ('room', models.CharField(max_length=10, verbose_name='Numero de habitacion')),
            ],
            options={
                'verbose_name': 'Reservacion',
                'verbose_name_plural': 'Reservaciones',
            },
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Hotel', 'verbose_name_plural': 'Hoteles'},
        ),
        migrations.AlterModelOptions(
            name='hotel_proveedor',
            options={'verbose_name': 'Proveedor de Hotele', 'verbose_name_plural': 'Proveerdores de Hoteles'},
        ),
        migrations.AlterModelOptions(
            name='restaurante',
            options={'verbose_name': 'Restaurante', 'verbose_name_plural': 'Restaurantes'},
        ),
        migrations.AlterModelOptions(
            name='restaurante_proveedor',
            options={'verbose_name': 'Proveedor de Restaurante', 'verbose_name_plural': 'Proveedor de Restaurantes'},
        ),
    ]
